apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
    kube-monkey/enabled: enabled
    kube-monkey/identifier: weather-app-deployment
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
        kube-monkey/enabled: enabled
        kube-monkey/identifier: weather-app-deployment
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: weather-app-container
        image: denisiuss/weather_argo:2be524b
        ports:
        - containerPort: 80
